version: '3'
services:
    web:
        image: nginx:1-alpine
        ports:
            - "8080:80"
        volumes:
            - ./code:/usr/share/nginx/html
            - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7.4-fpm
        volumes:
            - ./code:/usr/share/nginx/html